twig:
    paths:
        - '../src/BD2/Resources/views'
        - '../app/Resources/views'
    assets:
        bd2: 'assets/bd2'
        bootstrap: 'assets/bootstrap/dist'
        prism: 'assets/prism'

services:
    bd2.controller.page: '\BD2\Controller\PageController'
    bd2.controller.error: '\BD2\Controller\ErrorController'

error:
    service: 'bd2.controller.error'

pagination:
    results_per_page: 20
    templates:
        pagination: 'pagination.html.twig'
