twig:
    paths:
        - 'src/BD2/Resources/views'
        - 'app/Resources/views'
    assets:
        bd2: 'assets/bd2'
        bootstrap: 'assets/bootstrap/dist'
        prism: 'assets/prism'
        jquery.cookie: 'assets/jquery.cookie'

services:
    bd2.controller.page:
        class: '\BD2\Controller\PageController'
        tags:
            - 'bd2.controller'
    bd2.controller.error:
        class: '\BD2\Controller\ErrorController'
        tags:
            - 'bd2.controller'

error:
    service: 'bd2.controller.error'

pagination:
    results_per_page: 20
    templates:
        pagination: 'pagination.html.twig'

resources:
    root: 'src/BD2/Resources'
    files: 'files'