routes:
    introduction:
        type: 'match'
        route: '/'
        action: 'bd2.controller.page:introductionAction'
    introduction_paginated:
            type: 'get'
            route: '/page/{page}'
            action: 'bd2.controller.page:introductionAction'
            parameters:
                default:
                    - {page: 1}
                assert:
                    - {page: '\d+'}
    structure:
        type: 'match'
        route: '/struktura'
        action: 'bd2.controller.page:structureAction'
    data:
        type: 'match'
        route: '/dane'
        action: 'bd2.controller.page:dataAction'
    import:
        type: 'match'
        route: '/import'
        action: 'bd2.controller.page:importAction'
    analysis:
        type: 'match'
        route: '/analiza'
        action: 'bd2.controller.page:analysisAction'
    authors:
        type: 'match'
        route: '/autorzy'
        action: 'bd2.controller.page:authorsAction'
